config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks
  end
  root 'projects#index'
  resources :admin

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  acts_as_taggable
  acts_as_taggable_on :tags

  state_machine :initial => :new do
  
    event :checked do
      transition :new => :work
      transition :work => :verification
      transition :verification => :done
      transition :done => :using
    end

    state :new do
    end

    state :work do
    end

    state :verification do
    end

    state :done do
    end

    state :using do
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def new
    @admin = User.new
  end

  def create
    @admin = User.create!(user_params)
    @admin.save
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:new, :create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = @project.tasks.new
    @tasks = @project.tasks.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @user = User.find @task.current_user_id
  end

  # GET /tasks/new
  def new
    @project = Project.find params[:project_id]
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find params[:project_id]
    @task = Task.find params[:id]
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find params[:project_id]
    @task = @project.tasks.build(task_params)
    @task.current_user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :rating, :description, :state, :user_id, :tag_list)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def authenticate_admin!
    if current_user.status != true then
      redirect_to root_path
    end
  end

  def authenticate_admin?
    if current_user.status == true then
      return true
    else
      return false
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/new.html.erb
<h2>Sign up</h2>

<%= form_for @admin, url: admin_index_path do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasktracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  body

    == yield

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = select("project", "user_id", User.all.collect {|p| [ p.email, p.id ] }, {include_blank: 'None'})
  .actions = f.submit

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
section.row
  - if authenticate_admin? then
    = link_to 'New user', new_admin_path
    br
    = link_to 'New Project', new_project_path

- @projects.each do |project|

  section(id='p#{project.id}' class='row')
    h1 = project.name
    article.large-2.columns#new
      h3 New
      - project.tasks.each do |task|
        - if task.state == "new"
          = render task

    article.large-2.columns#work
      h3 Work
      - project.tasks.each do |task|
        - if task.state == "work"
          = render task

    article.large-2.columns#verification
      h3 Verification 
      - project.tasks.each do |task|
        - if task.state == "verification"
          = render task  

    article.large-2.columns#done
      h3 Done
      - project.tasks.each do |task|
        - if task.state == "done"
          = render task

    article.large-2.columns#using
      h3 Using
      - project.tasks.each do |task|
        - if task.state == "using"
          = task.title

    article.large-2.columns
      h3 Settings
      ul
        li = link_to 'New Task', new_project_task_path(project)
        li = link_to 'Edit Project', edit_project_path(project)
        li = link_to 'Destroy Project', project, data: {:confirm => 'Are you shure?'}, :method => :delete

app/views/projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.slim
p#notice = notice

p
  strong Name:
  = @project.name

p
  strong Tasks:
  = @project.tasks.count
  - if @project.tasks.any?
    = render @tasks 

p
  strong new_task
  = render 'tasks/form'

= link_to 'Edit', edit_project_path(@project)
'|
= link_to 'Back', projects_path

app/views/tasks/_form.html.slim
= form_for [@project, @task] do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :rating
    = f.number_field :rating
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :user_id
    = select("task", "user_id", User.all.collect {|u| [ u.email, u.id ]}, {include_blacnk: 'None'})
  .field
    = f.label :tag_list
    = f.text_field :tag_list
  = hidden_field(:task, :project_id)
  .actions = f.submit

app/views/tasks/_task.html.slim
article(id='#{task.id}')
  = link_to project_task_path(task.project, task)
    = task.title
  br
  = link_to 'Edit', edit_project_task_path(task.project, task)
  br
  = link_to 'Destroy', project_task_path(task.project, task), data: {:cofirm => 'Are you shure?'}, :method => :delete
  = form_for task.project,url: project_task_path(task.project, task), remote: true do |f|
    - case task.state
    - when "new"
      = hidden_field(:task, :state, value:'work')
    - when "work"
      = hidden_field(:task, :state, value:'verification')
    - when "verification"
      = hidden_field(:task, :state, value:'done')
    - when "done"
      = hidden_field(:task, :state, value:'using')
    - else
      = hidden_field(:task, :state, value:'using')
    = f.submit value: "Done"
br

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

= link_to 'Show', project_task_path(@task.project, @task)
'|
= link_to 'Back', root_path

app/views/tasks/index.html.slim
h1 Listing tasks

table
  thead
    tr
      th Title
      th Rating
      th Description
      th
      th
      th

  tbody
    - @tasks.each do |task|
      tr
        td = task.title
        td = task.rating
        td = task.description
        td = link_to 'Show', task
        td = link_to 'Edit', edit_task_path(task)
        td = link_to 'Destroy', task, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', root_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Title:
  = @task.title
p
  strong Rating:
  = @task.rating
p
  strong Description:
  = @task.description

p
  strong Creator:
  = @user.email

p
  strong Performer:
  = @task.user.email

p
  strong Tags:
  = @task.tag_list

= link_to 'Edit', edit_project_task_path(@task.project, @task)
'|
= link_to 'Back', root_path

app/views/tasks/update.js.erb
var task = $("article#<%= @task.id %>");
task.detach();
$("section#p<%= @task.project_id %> article#<%= @task.state %>").append("<%= j ( render @task )%>");